import {build} from 'esbuild';
import test from 'node:test';
import {JSDOM} from 'jsdom';
import assert from 'node:assert/strict';
import {readFile,writeFile} from 'node:fs/promises';
test('page parses locally and copies exact values without network or storage', async()=>{
const r=await build({entryPoints:['src/account-page.ts'],bundle:true,write:false,platform:'node',format:'esm',loader:{'.txt':'text'}});
const {accountPageResponse}=await import('data:text/javascript;base64,'+Buffer.from(r.outputFiles[0].text).toString('base64'));
const response=accountPageResponse();
assert.match(response.headers.get('content-security-policy'),/connect-src 'none'/);
const html=await response.text();
const dom=new JSDOM(html,{url:'https://x-utility.example/account-format',runScripts:'outside-only'});
const {window:w}=dom;let copied='',network=0;
w.fetch=()=>{network++;throw new Error('network forbidden')};
w.XMLHttpRequest=class {constructor(){network++;throw new Error('network forbidden')}};
Object.defineProperty(w.navigator,'clipboard',{value:{writeText:async value=>{copied=value}}});
w.eval(await readFile('src/generated/account-browser.txt','utf8'));
const q=s=>w.document.querySelector(s),auth='a'.repeat(40),totp='JBSWY3DPEHPK3PXP';
q('#account').value=`sample_user: Pass908! :sample@outlook.com:Mail908!:${totp}:${auth}`;
q('#template').value='Login:Password:Mail:MailPass:2FA:Token';
q('#parse').click();assert.equal(q('#results').hidden,false);assert.equal(q('#error').textContent,'');
assert.equal(w.document.querySelectorAll('#fields .field').length,6);
w.document.querySelectorAll('#fields button')[1].click();await new Promise(r=>setImmediate(r));
assert.equal(copied,' Pass908! ');assert.match(q('#status').textContent,/コピーしました/);
w.navigator.clipboard.writeText=async()=>{throw new Error('denied')};
w.document.querySelectorAll('#fields button')[1].click();await new Promise(r=>setImmediate(r));
assert.match(q('#status').textContent,/コピーできません/);
assert.equal(w.document.querySelectorAll('body > textarea').length,0);
q('#clear').click();assert.equal(q('#account').value,'');assert.equal(q('#fields').children.length,0);assert.equal(q('#results').hidden,true);
q('#product-filter').value='https://hstora.com/en/product/4841';q('#product-filter').dispatchEvent(new w.Event('input'));
assert.equal(q('#product').value,'4841');
q('#account').value=`sample_user----Pass908!----sample@outlook.com----${totp}----${auth}`;q('#parse').click();
assert.equal(w.document.querySelectorAll('#fields .field').length,5);
assert.equal(network,0);assert.equal(w.localStorage.length,0);assert.equal(w.sessionStorage.length,0);
q('#clear').click();q('#product-filter').value='';q('#product-filter').dispatchEvent(new w.Event('input'));q('#product').value='';
q('#template').value='User:Pass:Mail:MailPass:Token';q('#account').value=`sample_user:<img src=x onerror=alert(1)>:sample@outlook.com:Mail908!:${auth}`;q('#parse').click();
assert.equal(w.document.querySelectorAll('#fields img').length,0);
assert.equal(w.document.querySelectorAll('#fields input')[1].value,'<img src=x onerror=alert(1)>');

w.close();
});
