import { TUTORIAL_HTML } from "./login-tutorial-markup";
import browserScript from "./generated/account-browser.txt";

export function accountPageResponse(script = false): Response {
  const headers = {
    "Content-Type": script ? "application/javascript; charset=utf-8" : "text/html; charset=utf-8",
    "Cache-Control": "no-store", "Referrer-Policy": "no-referrer",
    "X-Content-Type-Options": "nosniff",
    "Content-Security-Policy": "default-src 'none'; script-src 'self'; style-src 'unsafe-inline'; connect-src 'none'; img-src 'none'; frame-ancestors 'none'; form-action 'none'; base-uri 'none'",
    "Permissions-Policy": "clipboard-write=(self)"
  };
  return new Response(script ? browserScript : `<!doctype html><html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>X アカウント形式判別 | X-Utility</title><style>
  *{box-sizing:border-box}body{margin:0;background:#0b0d12;color:#edf0f8;font:16px/1.65 system-ui,sans-serif}main{max-width:860px;margin:auto;padding:32px 18px 70px}h1{font-size:26px;margin:4px 0 12px}h2{font-size:20px}.tutorial-head{display:flex;justify-content:space-between;align-items:center;gap:12px}.tutorial-steps{list-style:none;padding:0;margin:0}.tutorial-steps li{padding:16px 0;border-top:1px solid #303747}.tutorial-steps h3{margin:8px 0;font-size:18px}.tutorial-steps button{margin-top:10px}.tutorial-steps select{margin-bottom:8px}.muted{font-size:14px}.confirm{display:flex;align-items:flex-start;gap:10px;font-size:14px}.confirm input{width:20px;min-width:20px;height:20px;margin-top:3px}#tutorial-code{font-size:30px;letter-spacing:6px;font-family:ui-monospace,monospace}#tutorial-countdown{color:#86ccaa}p{color:#b1bacb}section{background:#151922;border:1px solid #303747;border-radius:18px;padding:20px;margin:20px 0}label{display:block;font-weight:600;margin:14px 0 6px}input,textarea,select{width:100%;padding:13px;background:#0b0d12;border:1px solid #3d4659;border-radius:10px;color:inherit;font:inherit}textarea{min-height:140px;font:14px/1.6 ui-monospace,monospace;overflow-wrap:anywhere}button{min-height:46px;padding:10px 16px;background:#253247;border:1px solid #455777;border-radius:10px;color:#fff;font:inherit;cursor:pointer}button.primary{background:#2676dd;border-color:#2676dd}button:focus-visible,input:focus-visible,select:focus-visible,textarea:focus-visible{outline:3px solid #79b8ff;outline-offset:2px}.actions{display:flex;gap:10px;flex-wrap:wrap;margin-top:18px}.field{border-top:1px solid #303747;padding:14px 0;display:grid;grid-template-columns:1fr auto;gap:8px;align-items:center}.field input{grid-column:1/-1;font-family:ui-monospace,monospace}.field small{color:#c0a157}.field label{margin:0}.badge{font-size:12px;color:#83b7ff;letter-spacing:2px}.warning{color:#ffd288;white-space:pre-line}#status{min-height:28px;color:#86ccaa}#error{color:#ffa3a3;white-space:pre-line}summary{cursor:pointer;color:#b1bacb}a{color:#89beff;overflow-wrap:anywhere}#sources{font-size:13px}#source-info{white-space:pre-line;font-size:13px;color:#b1bacb}button[disabled]{opacity:.5;cursor:default}@media(max-width:500px){main{padding-top:22px}section{padding:16px}h1{font-size:23px}}
  </style><script src="/account-format.js" defer></script></head><body><main><span class="badge">X UTILITY</span><h1>X アカウント形式判別</h1><p>納品された文字列を貼り付けると、ID・パスワード・メール・2FAキーを一覧に整理できます。各項目はボタンでコピーできます。</p><p>入力はこの画面内だけで処理します。送信・保存・ログインは行いません。</p><section><label for="account">アカウントの納品文字列</label><textarea id="account" maxlength="4000" placeholder="1アカウント分を貼り付け" autocomplete="off" autocapitalize="off" spellcheck="false"></textarea><details><summary>購入元・Format・区切り文字を指定する</summary><label for="product-filter">購入元を検索（商品URL・商品ID・ショップ名）</label><input id="product-filter" type="search" autocomplete="off"><label for="product">購入元の商品</label><select id="product"></select><p id="source-info"></p><label for="template">商品説明のFormat（任意）</label><input id="template" placeholder="Login:Password:Email:EmailPassword:2FA:Token" autocomplete="off" spellcheck="false"><label for="separator">区切り文字（任意・判別候補を絞る）</label><select id="separator"><option value="">自動</option><option value=":">:</option><option value="|">|</option><option value="----">----</option><option value="---">---</option><option value="--">--</option><option value="-">-</option><option value=".">.</option><option value=",">,</option><option value=";">;</option><option value="::">::</option><option value="&#9;">タブ</option></select></details><div class="actions"><button id="parse" class="primary" type="button">判別する</button><button id="clear" type="button">入力・結果を消す</button></div><div id="error" role="alert"></div></section><section id="results" hidden><h2>判別結果</h2><p id="warning" class="warning"></p><label id="candidate-label" for="candidate" hidden>形式の候補（購入元のFormatと照合して選択）</label><select id="candidate" hidden></select><p id="sources"></p><div id="fields"></div><div class="actions"><button id="tutorial-show" type="button" class="primary" aria-expanded="false" aria-controls="tutorial">チュートリアルを表示</button></div></section>${TUTORIAL_HTML}<div id="status" role="status" aria-live="polite"></div><p id="coverage"></p><p>未判別や候補の項目は購入元の説明と照合してください。表示名は修正できます。キーやパスワードの有効性は、この画面では確認しません。</p></main></body></html>`, { headers });
}
